apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/red-hat-data-services/notebooks?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    build.appstudio.openshift.io/build-nudge-files: "manifests/base/params-latest.env"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push"
      && target_branch == "rhoai-2.22"
      && ( (!".tekton/**".pathChanged() || ".tekton/odh-workbench-jupyter-minimal-cuda-py311-ubi9-n-v2-22-push.yaml".pathChanged()) ||
         ("jupyter/utils/**".pathChanged() || "jupyter/minimal/ubi9-python-3.11/**".pathChanged() || "cuda/**".pathChanged()) )
      && !"manifests/base/params-latest.env".pathChanged()
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: external-rhoai-v2-22
    appstudio.openshift.io/component: odh-workbench-jupyter-minimal-cuda-py311-ubi9-n-v2-22
    pipelines.appstudio.openshift.io/type: build
  name: odh-workbench-jupyter-minimal-cuda-py311-ubi9-n-v2-22-on-push
  namespace: rhoai-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/modh/odh-workbench-jupyter-minimal-cuda-py311-ubi9:{{target_branch}}
  - name: additional-tags
    value:
    - '{{target_branch}}-{{revision}}'
  - name: dockerfile
    value: jupyter/minimal/ubi9-python-3.11/Dockerfile.cuda
  - name: path-context
    value: .
  - name: hermetic
    value: false
  - name: build-source-image
    value: false
  - name: build-image-index
    value: false
  - name: rebuild
    value: true
  - name: skip-checks
    value: true
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/red-hat-data-services/konflux-central.git
    - name: revision
      value: '{{ target_branch }}'
    - name: pathInRepo
      value: pipelines/container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-workbench-jupyter-minimal-cuda-py311-ubi9-n-v2-22
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
